import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import Menu from '../src/patterns/Menu';
import Footer from '../src/patterns/Footer';

function MyApp({ Component, pageProps }: AppProps) {
  const [activeTheme, setActiveTheme] = useState("dark");
  const inactiveTheme = activeTheme === "light" ? "dark" : "light";
  useEffect(() => {
    document.body.dataset.theme = activeTheme;
  }, [activeTheme]);
  return (
    <>
      <Head>
        <title>JBcamps DEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <!-- Google tag (gtag.js) --> */}
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-WSQM53XWN4"></script>
        <script 
          id="google-analytics"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());

              gtag('config', 'G-WSQM53XWN4');
            `,
          }}
        />
      </Head>
      <Menu />
      <Component {...pageProps} />
      <Footer />
    </>
    
  )
}

export default MyApp
