import '../styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { useEffect, useState } from 'react';
import Menu from '../src/patterns/Menu';
import Footer from '../src/patterns/Footer';
import Script from 'next/script';

function MyApp({ Component, pageProps }: AppProps) {
  const [activeTheme, setActiveTheme] = useState("dark");
  const inactiveTheme = activeTheme === "light" ? "dark" : "light";
  useEffect(() => {
    document.body.dataset.theme = activeTheme;
  }, [activeTheme]);
  return (
    <>
      {/* <!-- Google tag (gtag.js) --> */}
      <Script async src="https://www.googletagmanager.com/gtag/js?id=G-WSQM53XWN4"></Script>
      <Script 
        id="google-analytics"
        dangerouslySetInnerHTML={{
          __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());

            gtag('config', 'G-WSQM53XWN4');
          `,
        }}
      />
      <Head>
        <title>JBcamps DEV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>
      <Menu />
      <Component {...pageProps} />
      <Footer />
    </>
    
  )
}

export default MyApp
